---
Admin.paging: |
    50
    
Clipping.site_title: |
    <p>Press Release Distribution by EmailWire</p>
    
EmailTemplate.from_email: |
    hiteshvermadoit@gmail.com
    
Featured.Home.latest.limit: |
    <p>5</p>
    
Featured.Pr.limit: |
    <p>5</p>
    
Sidebar.Display.Advertisement: |
    <p>3</p>
    
Site.address: |
    <p><strong>EmailWire&trade; dba GroupWeb Media LLC</strong><br />
    Houston, TX 77060<br />
    Tel: 832-716-2363</p>
    
Site.admin_email: |
    hiteshvermadoit@gmail.com
    
Site.Copyright: |
    EmailWire is&nbsp;the global newswire with press release distribution, writing and media planning services. Amplify your news releases and reach your local or global target audience on any media platform. Press release distribution with guaranteed results&trade; GroupWeb Media LLC 2006 - ##YEAR##&nbsp; All rights reserved.
    
Site.currency: $
Site.DateFromat: M d, Y
Site.Default.Selected.Plan: |
    online-distribution
    
Site.Environment: |
    production
    
Site.headline.generator: |
    <p>Santexgroup RSS Generator</p>
    
Site.mail: |
    hiteshvermadoit@gmail.com
    
Site.name: |
    <p>EmailWire</p>
    
Site.newsroom.amount: 49
Site.newsroom.page.limit: |
    10
    
Site.paging: |
    50
    
Site.Payment.currency: |
    <p>USD</p>
    
Site.payment.environment: sandbox
Site.payment.live.url: https://www.paypal.com/cgi-bin/webscr
Site.payment.merchantId: 289z72hzb2px4py5
Site.payment.privateKey: decfcd4ed373ff5eabfa9deaaba9606d
Site.payment.publicKey: wmx8g72y79wzdgv4
Site.payment.sandbox.url: https://www.sandbox.paypal.com/cgi-bin/webscr
Site.Paypal.business.email: |
    sb-vv4343t28037@business.example.com
    
    
    &nbsp;
    
    
Site.phone: |
    <p>832-716-2363</p>
    
Site.PR.agreement : |
    <p>Pricing and Terms of Service&nbsp;</p>
    
    <p>GROUPWEB.COM provides affordable press release distribution, and accepts press releases in multimedia at no extra cost. Graphic thumbnails should be 100 by 100 pixels and high-resolution images should not be bigger than 600 by 600 pixels -- all in GIF or JPG formats. Audio or video clip can be up to 70 seconds long in real audio format.</p>
    
    <p>GROUPWEB.COM will publish your press release that is as long as 2000 words. However, all prices described at our price list section are for press releases with up to 400 or 500 words respectively. There is a $75 charge per each additional 100 words except on certain offers.</p>
    
    <p>We prefer prepayment with credit cards, but we also bill clients via invoicing. If you are a first-time user and intend to pay through invoicing, you must pay $99 fee, download and complete application form for approval. There is no fee to first-time users who intend to pay with credit cards. All account holders are responsible to pay their invoices upon receipt. We reserve the right to change prices at anytime without prior notification.</p>
    
    <p>Please note that, for editorial reasons, we cannot guarantee that editors and publishers will select your release for a story. It is at their discretion to pick a release that will make news. However, we do guarantee that we will deliver your press release to news media and make it live on Emailwire.com and GroupWeb.com Network. We also cannot gurantee that search engines will index your press release, because we have no control over the decisions they make to index web pages, press releases or other web documents.</p>
    
    <p>GROUPWEB.COM will charge a minimum of $59 per press release that has been approved and made live on Emailwire.com. If you have posted a press release on Emailwire.com, but you wish to withdraw it before it is approved, please notify our editors by calling 619-284-8011.</p>
    
    <p>GROUPWEB.COM reserves the right not to approve press releases posted on Emailwire.com.</p>
    
    <p>GROUPWEB.COM and PR Newswire facilities are governed by Federal and State regulations. You are responsible for the content and accuracy of all news copy and information submitted to PR Newswire via GROUPWEB.COM. Because of the volume of copy and information submitted to PR Newswire via GROUPWEB.COM, PR Newswire and GROUPWEB.COM cannot be responsible for verifying any facts contained therein.</p>
    
    <p>You represent and warrant to PR Newswire and GROUPWEB.COM that (i) You have the right to deliver to PR Newswire and GROUPWEB.COM all copy and information You submit, (ii) You will comply with all applicable laws, rules and regulations, including but not limited to the Children&#39;s Online Privacy Protection Act of 1998 and laws relating to <strong>spam</strong>, and (iii) no copy or information submitted by You will contain any content that is obscene, libelous, slanderous or otherwise defamatory, false or misleading or which violates any copyright, right of privacy or publicity or other right of any person. You shall indemnify and hold harmless PR Newswire, its affiliated companies, third party vendors, including distributors, and GROUPWEB.COM from and against any and all claims, losses, damages, liabilities, costs and expenses (including reasonable attorneys fees) arising out of or relating to any breach by You of the foregoing representations and warranties or otherwise arising out of or relating to the contents or nature of the information and/or copy provided by You.</p>
    
    <p>PR Newswire reserves the right to reject or edit copy or other information when necessary in its judgment. All news copy, photographs, video and audio files processed shall be the property of PR Newswire. PR Newswire and GROUPWEB.COM endeavor to disseminate promptly and accurately all news and other information that they process. Any inadvertent errors by PR Newswire or GROUPWEB.COM will be corrected promptly upon discovery, without additional charge, and such obligation to correct shall constitute the sole liability of PR Newswire and GROUPWEB.COM in this regard. PR Newswire and GROUPWEB.COM are not warranting or insuring that PR Newswire&#39;s or GROUPWEB.COM&#39;s services will be free from errors, omissions, interruptions, delay, losses or defects, whether human or mechanical.</p>
    
    <p>PR Newswire and GROUPWEB.COM make no warranties, expressed or implied, as to the services, including but not limited to any warranties or merchantability or suitability for print or broadcast. In no event will PR Newswire or its affiliates or GROUPWEB.COM be LIABLE to You, including for any indirect, consequential, special, exemplary or incidental damages. By Your submission of copy and/or other information to PR Newswire via GROUPWEB.COM, You agree to be bound by the foregoing Conditions of Service.</p>
    
    <p>If you&#39;ve read and agreed on the terms above, please click on the <strong>I Agree</strong> radio button below, then proceed to post your press release(s).</p>
    
Site.Seo.type: |
    <p>Organization</p>
    
Site.skype: groupwebmedia
Site.SwiftMailerPassword: |
    WPiO[Z@n,M23
    
Site.SwiftMailerUsername: |
    smtp@devsite.emailwire.com
    
Smtp.timeout: 200
Social.link.facebook: |
    <p>https://www.facebook.com/emailwire</p>
    
Social.link.linkedIn: |
    <p>https://www.linkedin.com/in/emailwire-web-aa2162190/</p>
    
Social.link.pintrest: |
    <p>https://in.pinterest.com/emailwire/</p>
    
Social.link.twitter: |
    <p>https://twitter.com/emailwire</p>
    
Social.link.youtube: |
    <p>https://www.youtube.com/user/EmailWire</p>
    
Social.media.api.url: https://onlywire.com/api/v2/
Social.media.password: |
    <p>&amp;.*Owire888?</p>
    
Social.media.username: onlywire
